DROP DATABASE IF EXISTS DBBANCOIDEIA;

CREATE DATABASE DBBANCOIDEIA;

USE DBBANCOIDEIA;

CREATE TABLE PROFESSOR (
    IDPROFESSOR INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(100),
    EMAIL VARCHAR(150),
    TELEFONE VARCHAR(15),
    CONSTRAINT PK_PROFESSOR PRIMARY KEY (IDPROFESSOR)
);

CREATE TABLE ALUNO (
    IDALUNO INT NOT NULL AUTO_INCREMENT,
    NOMT VARCHAR(100),
    EMAIL VARCHAR(150),
    TELEFONE VARCHAR(15),
    CONSTRAINT PK_ALUNO PRIMARY KEY (IDALUNO)
);

CREATE TABLE SOLICITANTE (
    IDSOLICITANTE INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(100),
    EMAIL VARCHAR(150),
    TELEFONE VARCHAR(15),
    CONSTRAINT PK_SOLICITANTE PRIMARY KEY (IDSOLICITANTE)
);

CREATE TABLE IDEIA (
    IDIDEIA INT NOT NULL AUTO_INCREMENT,
    IDSOLICITANTE INT NOT NULL,
    TEMA VARCHAR(255),
    DESCRICAO VARCHAR(255),
    DT_CADASTRO DATETIME,
    CONSTRAINT PK_IDEIA PRIMARY KEY (IDIDEIA),
    CONSTRAINT FK_IDEIA_SOLICITANTE FOREIGN KEY (IDSOLICITANTE) REFERENCES SOLICITANTE (IDSOLICITANTE)
);

CREATE TABLE INTERESSE_DESENVOLVER(
    IDIDEIA INT NOT NULL,
    IDALUNO INT NOT NULL,
    CONSTRAINT PK_INTERESSE_DESENVOLVER PRIMARY KEY (IDIDEIA, IDALUNO),
    CONSTRAINT FK_INTERESSE_DESENVOLVER_IDEIA FOREIGN KEY (IDIDEIA) REFERENCES IDEIA (IDIDEIA),
    CONSTRAINT FK_INTERESSE_DESENVOLVER_ALUNO FOREIGN KEY (IDALUNO) REFERENCES ALUNO (IDALUNO)
);

CREATE TABLE INTERESSE_ORIENTAR(
    IDIDEIA INT NOT NULL,
    IDPROFESSOR INT NOT NULL,
    CONSTRAINT PK_INTERESSE_ORIENTAR PRIMARY KEY (IDIDEIA, IDPROFESSOR),
    CONSTRAINT FK_INTERESSE_ORIENTAR_IDEIA FOREIGN KEY (IDIDEIA) REFERENCES IDEIA (IDIDEIA),
    CONSTRAINT FK_INTERESSE_ORIENTAR_PROFESSOR FOREIGN KEY (IDPROFESSOR) REFERENCES PROFESSOR (IDPROFESSOR)
);


