DROP DATABASE IF EXISTS DBBANCOIDEIA;

CREATE DATABASE DBBANCOIDEIA;

USE DBBANCOIDEIA;

CREATE TABLE PROFESSOR (
    IDPROFESSOR INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100),
    EMAIL VARCHAR(150),
    TELEFONE VARCHAR(15)
);

CREATE TABLE ALUNO (
    IDALUNO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOMT VARCHAR(100),
    EMAIL VARCHAR(150),
    TELEFONE VARCHAR(15)
);

CREATE TABLE SOLICITANTE (
    IDSOLICITANTE INT NOT NULL PRIMARY KEY PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100),
    EMAIL VARCHAR(150),
    TELEFONE VARCHAR(15)
);

CREATE TABLE IDEIA (
    IDIDEIA INT NOT NULL PRIMARY KEY AUTO_INCREMENTE,
    IDSOLICITANTE INT NOT NULL,
    TEMA VARCHAR(255),
    DESCRICAO VARCHAR(255),
    DT_CADASTRO DATETIME,
    CONSTRAINT FK_IDEIA_SOLICITANTE FOREIGN KEY(IDSOLICITANTE) REFERENCES SOLICITANTE (IDSOLICITANTE)
);

CREATE TABLE INTERESSE_DESENVOLVER(
    IDIDEIA INT NOT NULL,
    IDALUNO INT NOT NULL,
    CONSTRAINT PK_INTERESSE_DESENVOLVER PRIMARY KEY(IDIDEIA, IDALUNO),
    CONSTRAINT PK_INTERESSE_DESENVOLVER_IDEIA FOREIGN KEY(IDIDEIA) REFERENCES IDEIA (IDIDEIA),
    CONSTRAINT PK_INTERESSE_DESENVOLVER_ALUNO FOREIGN KEY(IDALUNO) REFERENCES ALUNO (IDALUNO)
);

CREATE TABLE INTERESSE_ORIENTAR(
    IDIDEIA INT NOT NULL,
    IDPROFESSOR INT NOT NULL,
    CONSTRAINT PK_INTERESSE_ORIENTAR PRIMARY KEY(IDIDEIA, IDPROFESSOR),
    CONSTRAINT PK_INTERESSE_ORIENTAR FOREIGN KEY(IDIDEIA) REFERENCES IDEIA (IDIDEIA),
    CONSTRAINT PK_INTERESSE_ORIENTAR FOREIGN KEY(IDPROFESSOR) REFERENCES PROFESSOR (IDPROFESSOR)
);


